# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0dec3398733f76b4633d49c575b9e62afc320e159ab621b246f465068ea299e27bf2784867443753c9948f4beba21efa56a03a22844e70fd4d381e395a8dd9a

test:
  secret_key_base: a31530408f8d0fb46faa12202ebc36eb46b5845f10834fb321a469b74f248cd1a399eb12053d4d687e94cdc9282022bc6f29c7d4946071485bb26659f8b8dde6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
